### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by wooddii** [tandasat/MemoryMon#5]
Hello!
Where can I find the files of the rootkit that is used in demo video https://www.youtube.com/watch?v=O5_ocsplrfA?

**Comment by tandasat** [comment]
This is the hash information of the file.
SHA-1 | 9e327408fedb128b5717cf0f0093756132624951
SHA-256 | c55fa19ac18710c56045e39724f3b6a83a916508ae23a14bb2a108e71eac64a0

If you have a VirusTotal Intelligence account, you can download from there. You could also find the sample some other online analysis service. If not, it might work if you try other sample but with the exact same detection name. They will likely to act in the same way, so the end results would be the same.
